services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
      - /app/node_modules
    depends_on:
      - backend
    command: sh -c "npm install && npm start"
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env.dev
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app/backend
    command: >
      sh -c "python /app/backend/server/manage.py migrate && python /app/backend/server/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
volumes:
   static_volume: {}
   mysql_data: {}
